apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-autentificacion-ingress
  namespace: ambulancia-system
  labels:
    app: ms-autentificacion
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - auth.ambulancia.local
    secretName: ms-autentificacion-tls
  rules:
  - host: auth.ambulancia.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ms-autentificacion
            port:
              number: 80
